name: my-environment
channels:
  - conda-forge
  - https://prefix.dev/sofa-framework
dependencies:
  - python=3.12
  - matplotlib
  - bokeh
  - jupyter_bokeh
  - k3d
  - numpy
  - sympy
  - sofa-python3