name: my-environment
channels:
  - conda-forge
  - https://prefix.dev/sofa-framework
dependencies:
  - python=3.12
  - jupyter
  - jupytext
  - matplotlib
  - bokeh
  - jupyter_bokeh
  - k3d
  - pyvista[all,trame]
  - numpy
  - sympy
  - sofa-python3
  - sofa-glfw
  - sofa-softrobots
  - sofa-softrobotsinverse