name: my-environment
channels:
  - emscripten-forge
  - conda-forge
  - https://prefix.dev/sofa-framework
dependencies:
  - python=3.12
  - xeus-python # A Jupyter kernel for Python
  - matplotlib
  - k3d
  - numpy
  - sofa-python3